apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: my-tkc #name of cluster
  namespace: ns01
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall # vmclass to be used for master(s)
      storageClass: k8s-policy
    workers:
      count: 2
      class: best-effort-xsmall # vmclass to be used for workers(s)
      storageClass: k8s-policy
  distribution:
    version: v1.16.8
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
