apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nsx-demo-policy
spec:
  podSelector:
    matchLabels:
      app: yelb-db
      tier: backenddb
#      ports:
#      - port: 5432
#        protocol: TCP
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            app: yelb-ui
            tier: frontend
#    ports:
#      - port: 5432
#        protocol: TCP
