kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-ns_fusion-devteam
  namespace: fusion
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
#- kind: Group
#  name: sso:DevTeamA@lab.local
- kind: User
  name: sso:ldev@corp.local            #sso:<username>@<domain>
  apiGroup: rbac.authorization.k8s.io
