apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-xsmall
  namespace: svc
spec:
  distribution:
    version: v1.16.8
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: k8s-policy
    workers:
      count: 1
      class: best-effort-xsmall
      storageClass: k8s-policy
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
    storage:
      defaultClass: k8s-policy
