apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: svc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  # Replace name below with appropriate label for the policy
  name: jenkins-ns01-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: svc
